# Минимальная версия инфраструктуры на базе
# OpenSearch - хранилище логов и метрик
# OpenSearch Dashboards - отрисовка логов
# Fluent Bit - служба сбора логов
# Envoy - прокси
# Keycloak - сервер идентификации

# Адреса:
# Приложение доступно по http://localhost:8080 (envoy прокси)
# Панели мониторинга http://localhost:5601 (opensearch dashboards, kibana)
# Управление пользователями http://localhost:8081 (keycloak)

services:

  app:
    image: nginx:1.26.2-alpine-slim
#    depends_on:
#      - fluent-bit
#      - envoy
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/html:/usr/share/nginx/html
#    logging:
#      # используемый драйвер логгирования
#      driver: "fluentd"
#      options:
#        # куда посылать лог-сообщения, необходимо чтобы адрес
#        # совпадал с настройками плагина forward
#        fluentd-address: localhost:24224
#        # теги используются для маршрутизации лог-сообщений, тема
#        # маршрутизации будет рассмотрена ниже
#        tag: app.logs

#  fluent-bit:
#    container_name: fluent-bit
#    image: fluent/fluent-bit
#    ports:
#      # необходимо открыть порты, которые используются плагином forward
#      - "24224:24224"
#      - "24224:24224/udp"
#      - "2020:2020"
#    environment:
#      - opensearch_host=opensearch
#      - opensearch_user=admin
#      - opensearch_pass=adm-Password0
#    volumes:
#      - ./volumes/fluent-bit-etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
#      - ./volumes/fluent-bit-etc/parsers.conf:/fluent-bit/etc/parsers.conf
#
#  opensearch:
#    container_name: opensearch
#    image: opensearchproject/opensearch:latest
#    environment:
#      - discovery.type=single-node
#      - http.port=9200
#      - bootstrap.memory_lock=true
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=adm-Password0
#    ports:
#      - '9200:9200'
#      - '9600:9600'
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    volumes:
#      - opensearch-data:/usr/share/opensearch/data
#
#  dashboards:
#    image: opensearchproject/opensearch-dashboards:latest
#    container_name: opensearch-dashboards
#    ports:
#      - 5601:5601
#    expose:
#      - "5601"
#    environment:
#      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
#    depends_on:
#      - opensearch
#
  envoy:
    image: envoyproxy/envoy:v1.29.0
    volumes:
      - ./volumes/envoy/envoy.yaml:/etc/envoy/envoy.yaml
#      - ./volumes/envoy/certs:/etc/envoy/certs  # Mount your TLS certificates
    ports:
      - "8080:8080"
#      - "15001:15001"
    depends_on:
      keycloak:
        condition: service_healthy
    command:
      - -c
      - /etc/envoy/envoy.yaml
      - -l
      - debug

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    ports:
      - "8081:8080"
#      - "9000:9000"
    volumes:
      - ./volumes/keycloak/data:/opt/keycloak/data
#      - ./volumes/keycloak/certs/keycloak.jks:/etc/x509/https/keycloak.jks  # Mount your Keycloak keystore
    environment:
#      KEYCLOAK_USER: avetal
#      KEYCLOAK_PASSWORD: vasya1991
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3; grep 'HTTP/1.1 200 OK' <&3"]
      interval: 10s
      timeout: 5s
      retries: 15
    command:
      - start-dev
      - --proxy-headers=forwarded
      - --hostname-strict=false
#
#volumes:
#  opensearch-data:
